import Layouts from "@/components/Layout";
import { ShowModal } from "@/contexts/Modal";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { useState } from "react";
import MessageProvider from '@/components/Message'
import { AdminAuthProvider } from "@/utils/context/AdminAuth";

export default function App({ Component, pageProps }: AppProps) {
  const [isModalOpen, setModalOpen] = useState<boolean>(false);
  return <>
  <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <AdminAuthProvider>
       <MessageProvider>
        <ShowModal.Provider value={{ isModalOpen, setModalOpen }}>
            <Layouts>
            <Component {...pageProps} />
            </Layouts> 
          </ShowModal.Provider>

        </MessageProvider>
        </AdminAuthProvider>

  
  
  </>
  
}
